name: circle_camera_desktop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  camera_platform_interface: ^2.7.4
  camera_windows: ^0.2.2
  flutter:
    sdk: flutter
  get: ^4.6.6
  window_manager: ^0.3.8

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
